# Generated by Django 6.0.6 on 2026-06-30 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscription"),
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Добавьте ссылку на оплату",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Введите ID сессии",
                max_length=255,
                null=True,
                verbose_name="ID сессии",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите курс",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="materials.course",
                verbose_name="Оплаченный курс",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите урок",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="materials.lesson",
                verbose_name="Оплаченный урок",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("transfer_to_account", "Перевод на счет"),
                ],
                default="transfer_to_account",
                help_text="Выберите способ оплаты",
                max_length=50,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
